included:
  - AppSPM
  - VinAppleTV
  - VinAppleTVTests
  - VinAppleTVUITests

excluded:
  - "**/.build"
  - DerivedData

disabled_rules:
  - todo
  - trailing_whitespace

line_length:
  warning: 220
  error: 300
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 800
  error: 1200

type_body_length:
  warning: 400
  error: 600

function_body_length:
  warning: 60
  error: 100

function_parameter_count:
  warning: 8
  error: 10

identifier_name:
  excluded:
    - id
    - to

reporter: xcode
